runtime: python37

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

- url: /images
  static_dir: images

- url: /flags
  static_dir: flags

  
  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*

  script: auto

env_variables:
  CLOUD_SQL_CONNECTION_NAME: amir-nl:us-central1:db
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: fvisbaba1342
  CLOUD_SQL_DATABASE_NAME: site
  CLOUD_STORAGE_BUCKET: amir-nl
